export const environment = {
  production: false,
  platformProviderApiBaseUrl: 'https://agrotrack-mockapi.azurewebsites.net/api/v1',
  platformProviderSubscriptionsEndpointPath: '/subscriptions',
  platformProviderOrganizationsEndpointPath: '/organizations',
  platformProviderPlotsEndpointPath: '/plots',
  platformProviderPlantTypesEndpointPath: '/planttypes',
  platformProviderChecklistEndpointPath: '/checklist',
  platformProviderTaskEndpointPath: '/task',
  platformProviderPlantSamplingSessionsEndpointPath: '/plant-sampling-session',
  platformProviderPlantObservationEndpointPath: '/plantobservation',
  platformProviderEnvironmentalReadingEndpointPath: '/environmental-readings',
  platformProviderProfileEndpointPath: '/profile',
  platformProviderReportsEndpointPath: '/reports',
  weatherApiBaseUrl: 'https://api.weatherapi.com/v1',
  weatherApiKey: 'd8020360b6a448fe9e1172139250810',
  weatherApiDefaultLocation: 'Peru',
};
